package org.booklore.service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.booklore.model.dto.ReleaseNote;
import org.booklore.model.dto.VersionInfo;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.info.BuildProperties;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

@Slf4j
@Service
@AllArgsConstructor
public class VersionService {
    // Accepts a trailing "+<build>" so local builds (3.2.18+57) are still labelled like a tag.
    private static final Pattern VERSION_PATTERN = Pattern.compile("^\\d+\\.\\d+\\.\\d+(\\+\\d+)?$");
    private static final String DEVELOPMENT_VERSION = "development";
    private static final String UNKNOWN_VERSION = "unknown";
    private static final String GITHUB_REPO = "prakunin/booklib";
    private static final String BASE_URI = "https://api.github.com/repos/" + GITHUB_REPO;
    private static final int MAX_RELEASES = 15;
    private static final RestClient REST_CLIENT = RestClient.builder()
            .defaultHeader("Accept", "application/vnd.github+json")
            .defaultHeader("User-Agent", "BookLib-Version-Checker")
            .build();
    private final ObjectMapper objectMapper;
    /**
     * Optional: present whenever META-INF/build-info.properties was generated by the
     * Gradle build, which is the only version source available when running from
     * build/classes instead of a packaged jar.
     */
    private final ObjectProvider<BuildProperties> buildProperties;

    public String getAppVersion() {
        String appVersion = buildInfoVersion();

        if (appVersion == null) {
            appVersion = getClass().getPackage().getImplementationVersion();
        }

        if (appVersion == null) {
            return DEVELOPMENT_VERSION;
        }

        // If in X.Y.Z format, prefix with a `v` to match the tag.
        if (VERSION_PATTERN.matcher(appVersion).matches()) {
            appVersion = "v" + appVersion;
        }

        return appVersion;
    }

    private String buildInfoVersion() {
        BuildProperties properties = buildProperties.getIfAvailable();
        if (properties == null) {
            return null;
        }
        String version = properties.getVersion();
        return version == null || version.isBlank() ? null : version;
    }

    public VersionInfo getVersionInfo() {
        String latest = UNKNOWN_VERSION;
        try {
            latest = fetchLatestGitHubReleaseVersion();
        } catch (Exception _) {
            log.warn("Error fetching latest release version");
        }

        return new VersionInfo(getAppVersion(), latest);
    }

    public List<ReleaseNote> getChangelogSinceCurrentVersion() {
        return fetchReleaseNotesSince(getAppVersion());
    }


    public String fetchLatestGitHubReleaseVersion() {
        try {
            String response = REST_CLIENT.get()
                    .uri(BASE_URI + "/releases/latest")
                    .retrieve()
                    .body(String.class);

            JsonNode root = objectMapper.readTree(response);
            return root.path("tag_name").asString(UNKNOWN_VERSION);

        } catch (Exception _) {
            log.warn("Failed to fetch latest release version");
            return UNKNOWN_VERSION;
        }
    }

    public List<ReleaseNote> fetchReleaseNotesSince(String currentVersion) {
        if (DEVELOPMENT_VERSION.equals(currentVersion)) {
            log.warn("Skipping fetch of release notes because current version is '{}', which is a local development build.", currentVersion);
            return new ArrayList<>();
        }
        log.info("Fetching release notes since version: {}", currentVersion);

        List<ReleaseNote> updates = new ArrayList<>();
        try {
            String response = REST_CLIENT.get()
                    .uri(BASE_URI + "/releases?per_page=" + MAX_RELEASES)
                    .retrieve()
                    .body(String.class);

            JsonNode releases = objectMapper.readTree(response);
            if (!releases.isArray()) {
                log.warn("Invalid releases response from GitHub API");
                return updates;
            }

            for (JsonNode release : releases) {
                String tag = release.path("tag_name").asString(null);
                if (tag == null || !isVersionGreater(tag, currentVersion)) {
                    continue;
                }
                String url = "https://github.com/" + GITHUB_REPO + "/releases/tag/" + tag;
                LocalDateTime published = LocalDateTime.parse(release.path("published_at").asString(), DateTimeFormatter.ISO_DATE_TIME);
                updates.add(new ReleaseNote(tag, release.path("name").asString(tag), release.path("body").asString(""), url, published));
            }

            log.info("Returning {} newer releases", updates.size());

        } catch (Exception e) {
            log.error("Failed to fetch release notes", e);
        }

        return updates;
    }

    /**
     * Splits a version into its numeric segments, dropping the leading {@code v} and any
     * {@code +<build>} suffix — the local build counter is not part of the release ordering,
     * and leaving it in would make every comparison throw on {@code Integer.parseInt}.
     */
    private String[] numericParts(String version) {
        String normalized = version.replace("v", "");
        int buildSeparator = normalized.indexOf('+');
        if (buildSeparator >= 0) {
            normalized = normalized.substring(0, buildSeparator);
        }
        return normalized.split("\\.");
    }

    private boolean isVersionGreater(String version1, String version2) {
        try {
            String[] v1 = numericParts(version1);
            String[] v2 = numericParts(version2);
            for (int i = 0; i < Math.max(v1.length, v2.length); i++) {
                int num1 = i < v1.length ? Integer.parseInt(v1[i]) : 0;
                int num2 = i < v2.length ? Integer.parseInt(v2[i]) : 0;
                if (num1 > num2) return true;
                if (num1 < num2) return false;
            }
        } catch (Exception e) {
            log.error("Version comparison failed: {}", e.getMessage());
        }
        return false;
    }
}
