apiVersion: v2
name: booklib
description: A Helm chart for [BookLib](https://github.com/prakunin/booklib)
type: application
version: 0.1.0

# The app version tracks the latest stable release and is overridden
# dynamically by the CI on release (helm package --app-version)
appVersion: "v3.2.17"
dependencies:
  - name: mariadb
    version: 0.16.6
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
